

spring:
  datasource:
    url: jdbc:p6spy:mysql://10.0.0.6:3306/demo?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: zqc
    password: Zqchao2023

